### ISSUE TITLE
mathiasverraes/money dependency

### ISSUE THREAD

**Issue by cdarken** [antonienko/MoneyFormatter#4]
Hi.

I'm trying to use this lib with mathiasverraes/money dev-master or at least v1.3.0, but it needs 1.2.
Is that version really required? Or you could update it at least in master branch?

Thank you.

**Comment by ghost** [comment]
Here you go!

https://github.com/antonienko/MoneyFormatter/releases/tag/v1.3.1

**Comment by cdarken** [comment]
thank you!
